### ISSUE TITLE
Upgrade to django=>1.7

### ISSUE THREAD

**Issue by sveetch** [emencia/cookiecutter-djangocms3-buildout#15]
This is coming to be a problem to use django==1.6 because a lot of recent app versions search for the Django migrations system that is only available since 1.7 and so it break database install.

**Comment by slothyrulez** [comment]
created a branch named 'dj17' with my first effort towards Django 1.7

**Comment by sveetch** [comment]
Ok i finally started this issue with the first step in commit 9fe9522 on branch 'moving_to_django1_7'. I used @slothyrulez in buildout/version cfg files to start.

For now, i disabled all third apps/mods, keeped only the cms, zinnia and some other innocent and compatible app.

It run and works.

**Comment by slothyrulez** [comment]
Deleted branch 'dj17'

**Comment by sveetch** [comment]
So, still have to evolve some of our apps to django1.7:

* porticus;
* slideshow;
* cms snippet;
* socialaggregator;

First and second should be trivial. Snippet is not difficult but i have think about strategy (fork release package renamed?). Socialaggregator should be the most difficult because it rely on many libs than i dont know much about.

And finally from what i saw, seems the Django1.8 evolve should be more easy, than the 1.7 step.

**Comment by sveetch** [comment]
* Structure has been ported for Django1.7;
* Porticus port is done;
* Slideshows port is done;
* cms snippet port is done, still using our fork until our Pull request has been merged or not, will wait about some weeks for repository admin answers then do a new package if no answer is given.

Socialaggregator support has been canceled, since it's not used anymore in our present projects. So we start without it, and maybe port it to 1.7 on customer demand/requirement.

Now i just have to test it, review some eggs versions looking for mature and interesting updates and test it again. We should have the final release this week or next week end.

**Comment by sveetch** [comment]
Ok our snippet stuff has been released as package https://pypi.python.org/pypi/djangocms-snippet/1.7.1 this is a ready to use version with >=Django1.7, so now we can use it as a real egg.

**Comment by sveetch** [comment]
Bad news, i saw i still have to port emencia.django.countries, then our accounts app and the contact form.

**Comment by sveetch** [comment]
Here we are, the 0.9.0 (commit a84bb80) with Django==1.7 has been released

**Comment by jdavid** [comment]
:clap:
