### ISSUE TITLE
Upgrage to django1.8

### ISSUE THREAD

**Issue by slothyrulez** [emencia/cookiecutter-djangocms3-buildout#24]

**Comment by sveetch** [comment]
Yeah why not, but you should think first about getting support django 1.7 #15

**Comment by slothyrulez** [comment]
IMHO, i'll jump directly to 1.8 when django-cms starts to be usable on it

**Comment by sveetch** [comment]
Remember that there is a dozen of our apps to migrate to django >= 1.7 before

**Comment by slothyrulez** [comment]
created a branch named 'dj17' with my first effort towards Django 1.7
