### ISSUE TITLE
Better package name contest

### ISSUE THREAD

**Issue by slothyrulez** [emencia/cookiecutter-djangocms3-buildout#25]
Say cookiecutter-djangocms3-buildout is problematic, you can end up with a knot on the tongue

**Comment by sveetch** [comment]
Nowadays it's coming to be hard to find a single word name that does not allready exists. I dare your to find one that is highly related to the project. Launch a competition on our chan to have some ideas then validate it, we will see !

This will have to be a solid and strong name that everyone accept, because we wont change the project name every month.

**Comment by slothyrulez** [comment]
My proposal, Biscuits

**Comment by sveetch** [comment]
Please, make a strong search about the name so it does not allready exist on Github or Pypi

**Comment by slothyrulez** [comment]
Ok!, i'll take care

**Comment by slothyrulez** [comment]
- Sandwich
- Biscuits
- FooBaBaz

**Comment by slothyrulez** [comment]
Form our internal forum:

    Sandwich
    Biscuits
    FooBaBaz
    Barbeque
    Triki
    cookiecutter-djangocms3-buildout
    cookiecutter-djangocms3-buildout with surname or "A.K.A"
    Cheesecake
    Cupcake
    Donut
    Muffin

**Comment by sveetch** [comment]
Ok my bad, i will be a little picky about this but i suggested Sandwich, was not a real bad idea but it does not fit well with the meaning of a "cookiecutter". So i'm not confident anymore in this suggest.

Will be nice to find something complex as a sandwich but that is done using a cookiecutter (so probably with sugar), but i don't have any idea..

**Comment by sveetch** [comment]
Well, it was a nice idea but we are stuck with the current name and i dont have real arguments to justify a repository renaming.

Better to keep this name list if we do a really big change like dropping buildout for another tool.
