### ISSUE TITLE
About using pqsl backend on all environments

### ISSUE THREAD

**Issue by slothyrulez** [emencia/cookiecutter-djangocms3-buildout#26]
Postgresql for a development stages of a project as default database.

**Comment by sveetch** [comment]
Won't never happend as a default, not everybody want to install a postgres server, sqlite stay the easy way to start for everyone

**Comment by slothyrulez** [comment]
1 - As a good practice, is recommended to have the same environment on all stages of development.
2 - With django 1.8 postgresql has a contrib lib with sweet features
3 - Use postgres on dev makes devs to have strong knowledge on the same db used on production
4 - Learn make people smart and happy
5 - Postgresql can be as easy to use as sqlite

**Comment by slothyrulez** [comment]
May be is just find the way  to happen...

**Comment by sveetch** [comment]
Seems you forget our workmates that are not developers like kosac or kase. I will let you see with them how to install postgresql server and client.

**Comment by rage2000** [comment]
2/ and sqlite is more flexible when we need to share db with us (no need to reset db/inject sql)

**Comment by slothyrulez** [comment]
I always have them in my heart,  

1 - Having a psql server can help on remote assistance.
2 - Sergio uses a osx, maybe he can help on assist
3 - Import a dump can be as easy as push a button

**Comment by slothyrulez** [comment]
We can share dumps, Phillipe

**Comment by rage2000** [comment]
Dumps are not so agile. What is exactly the problem with sqlite ? It's working, it's simple and light, we almost never need postgres specificity.

**Comment by slothyrulez** [comment]
First comment resumes my point. But my strongest reason is all devs being more productive on hostile situations like a problem on production.

**Comment by sveetch** [comment]
@slothyrulez  I Think you say that probably because of etudes & events projects that are a little special. Think about that it is (at least for now) an uncommon situation. 

Using sqlite3 is fine for 90% of our projects because most of the time it's just integration and maybe some little tiny apps to dev, where psql instead of sqlite wont append any bonus.

Adding difficulty to install the project just for 10% of our project is not very usefull.

**Comment by rage2000** [comment]
etudes & events use postgresql on dev (and it's a problem with our integrators)

**Comment by slothyrulez** [comment]
Of course use a 'new' unknown thing comes with surprises, when we have a simple workflow of use  all that 'new' overhead will be paid when you have the 99% of the projects installable by any person. @rage2000 the same applies on that case, if they have already an easy workflow, they dont have any problem.
We are talking here about:
Install the server
Configure it
Have a command to do a dump on development, retrieve it and recover it locally

**Comment by sveetch** [comment]
Closing issue as a final "wontfix", only re-open it if you have some good feedback from roger and juan david :)
