### ISSUE TITLE
The sitemap mod duplicates the urls

### ISSUE THREAD

**Issue by jdavid** [emencia/cookiecutter-djangocms3-buildout#28]
At line https://github.com/emencia/cookiecutter-djangocms3-buildout/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/project/mods_available/sitemap/urls.py#L86

You can read (comments removed):

    urlpatterns += patterns('django.contrib.sitemaps.views',
        url(r'^sitemap\.xml$', 'sitemap', {'sitemaps': sitemaps}),
    ) + urlpatterns

This duplicates the urls. Either change the first **+=** to just **=** or remove the last **+ urlpatterns**
Depending on what you want to do, append or prepend. Probably you want to prepend since that is what we do almost everywhere else. So it should read (comments removed):

    urlpatterns = patterns('django.contrib.sitemaps.views',
        url(r'^sitemap\.xml$', 'sitemap', {'sitemaps': sitemaps}),
    ) + urlpatterns

**Comment by jdavid** [comment]
And the same error is just below, at https://github.com/emencia/cookiecutter-djangocms3-buildout/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/project/mods_available/sitemap/urls.py#L92

Except that it is commented.

**Comment by sveetch** [comment]
Oups, yes, nice catch, this is a stupid error, have to see if i did it also on other mods urls.
