### ISSUE TITLE
Mind about using Pavel instead of buildout

### ISSUE THREAD

**Issue by sveetch** [emencia/cookiecutter-djangocms3-buildout#30]
buildout is a little like "so 90's", Pavel system is more Python way.

But it's a huuuuuge work to move from buildout, so have to do a loooot of research&development to valid Pavel and integrate it without any loss.

Don't attempt anything for now, just play and search.

**Comment by jdavid** [comment]
Switching from Buildout to Pavel should be based only on problems Buildout has that Pavel solves, and nothing else.

By the way, Buildout development started in the 2000's. And what means "Python way"?

**Comment by rage2000** [comment]
Always the same debate.

Like jdavid, for me if we need to switch to a new tool, it's because this tools have new features that missing for us in the old one (or minimally implant features that we already use in simplest way), not because the new tool is "hyper" or "newest" 

Paver (and not pavel) remind me more a "make" tool in python. I'm not so sure that use it for replace buildout follows on something simpler.

**Comment by slothyrulez** [comment]
Quoting Sveetch:

'...Don't attempt anything for now, just play and search...'

I don't see anything bad on that approach, there are a lot of ways to 
have a web stack , and test others to try to improve ours is not a bad 
thing to me.

The hyper & newer/est thing is my fault, but i'm envisioning a new more 
conservative approach of that kind of things, there is a huge work done 
to arrive to the actual status, and it should be respected, but the 
debate on new tooling or news approaches does not mean that work is not 
respected / appreciated.

**Comment by sveetch** [comment]
Too many debates for nothing, this task was just to remind me about this idea for just giving head to another solution and optionnally having some ones to r&d with me on it.

But this is just about R&D, won't do nothing without good reasons to replace buildout.

I'm closing ticket since finally i can't have reminder without to be polluted

**Comment by jdavid** [comment]
Only the first sentence was troubling. Of course you can research whatever you want.
