### ISSUE TITLE
Node front & assets workflow

### ISSUE THREAD

**Issue by slothyrulez** [emencia/cookiecutter-djangocms3-buildout#40]
https://github.com/emencia/cookiecutter-djangocms3-buildout/tree/nodeworkflow

Have node / js on the "cookie" will allow us to react faster and adopt techs on this crazy fast changing world.
Does the idea worths ? 

This is an open "debate"

**Comment by sveetch** [comment]
I would mind about moving to a NodeJS asset manager if we validate usage of libsass with the Node wrapper http://sass-lang.com/libsass instead of Compass to compile our SCSS. 

And then this will be very interesting as we would drop Ruby and Java from our process and just use Node instead.

**Comment by sveetch** [comment]
Canceled since nobody at Emencia care about this anymore.
