### ISSUE TITLE
Mind about replacing Compass

### ISSUE THREAD

**Issue by sveetch** [emencia/cookiecutter-djangocms3-buildout#43]
Research and Development on the official libsass wrapper (the one done with Node.js).

Consider also Python wrapper if magic unicorn exists

**Comment by sveetch** [comment]
Libsass is just for sass, not all sugar mixins and stuff like Compass add on top of sass.

Choosing the right libsass wrapper (python, c/c++, node) depend on the wrapper that succeed to compile Foundation 5.x correctly, not more longer than Compass do it and watch mode have obviously to work.

The python wrapper is our prefered, because Python dependancies is the best for us. Another wrapper like the c/c++ one should be the strongest of all, but we also want some flexibility like with the Python wrapper.

Finally, we need to find a good sass mixins library (a real sass library, not a node.js/ruby one) to replace Compass mixins we will lose. It should not be the biggest difficulty as these mixins are not so much complicated and dont change often.

**Comment by slothyrulez** [comment]
http://www.hongkiat.com/blog/mixin-library-for-sass/
El 8/1/2016 19:32, David THENON <notifications@github.com> escribió:Libsass is just for sass, not all sugar mixins and stuff like Compass add on top of sass.

Choosing the right libsass wrapper (python, c/c++, node) depend on the wrapper that succeed to compile Foundation 5.x correctly, not more longer than Compass do it and watch mode have obviously to work.

The python wrapper is our prefered, because Python dependancies is the best for us. Another wrapper like the c/c++ one should be the strongest of all, but we also want some flexibility like with the Python wrapper.

Finally, we need to find a good sass mixins library (a real sass library, not a node.js/ruby one) to replace Compass mixins we will lose. It should not be the biggest difficulty as these mixins are not so much complicated and dont change often.

**Comment by sveetch** [comment]
@slothyrulez yeah that's the link i found yesterday but share only with bloxboy on private discuss, sorry

**Comment by sveetch** [comment]
It's important to notice that legacy libsass path resolving within imported library is different from Compass. And this seems the case also for node.js wrapper as Foundation5 source use this resolving behavior.

This lead to failing compile with sassc so i will have to ship a little script that i done to parse some sass sources to correct their included import paths.

**Comment by sveetch** [comment]
https://github.com/dahlia/libsass-python/issues/114

**Comment by sveetch** [comment]
Ok from what i tested, libsass python wrapper is validated. It compile Foundation5 with success, there is some `@import` path to change because relative path resolving is not exactly the same than with Compass, but it's a minor change.

Note also than unlike Compass, the watch mode only watch for only one main scss file given as sassc argument, not an entire directory. but this is not really important.

Now i just have to produce a clean structure with our scss cleaned, etc..

Would be interesting to try if libsass can compile our old compass stuff with Foundation 5.4 and even v3. It could be nice if everyone can just drop all the rvm/ruby/compass stuff and just install libsass.

**Comment by sveetch** [comment]
I stated we will use Bourbon. It's mature, full featured and well documented.

http://bourbon.io/

There is a glitch, Bourbon next big release will drop its vendor prefixes support in profit of Postcss+Autoprefixer usage. Having to use Node.js solutions is not so painfull as Ruby was but it would have been so much nicer to require multiple languages tools to do things right with CSS stuff.

**Comment by slothyrulez** [comment]
Lol
El 11/1/2016 11:02, David THENON <notifications@github.com> escribió:I stated we will use Bourbon. It's mature, full featured and well documented.

http://bourbon.io/

There is a glitch, Bourbon next big release will drop its vendor prefixes support in profit of Postcss+Autoprefixer usage. Having to use Node.js solutions is not so painfull as Ruby was but it would have been so much nicer to require multiple languages tools to do things right with CSS stuff.

**Comment by sveetch** [comment]
Please, this is not a chat/irc, if you have some argument or something useful, you are welcome, but this kind of comment you did is just disturbing for nothing.

**Comment by sveetch** [comment]
So i got a working structure using libsass and including foundation5 + bourbon, i just started to fix some things in our basic scss components and then i will open a libsass branch during i will remove all Compass stuff and add some things to easy libsass usage.

Some notes about this future:

* Bourbon has dropped some mixins like background-size, text-shadow, box-shadow, etc.. because it stand on "Can I Use" datas that demonstrate these properties are no longer needed (implemented in browsers since 2/3 years). Not a big deal but designers have to know about this.

* Current Bourbon version is 4.2.x, "vendor prefix dropping" is scheduled for 5.0.0, we have some time to think about it, and finally we could probably live with a freezed version on <5.x (it's just extra mixins);

* libsass is amazingly fast ! Something Compass do in 5seconds or more, libsass Python wrapper do it in less than 1second;

* libsass watch mode is working BUT for now it does not watch for change on included files, just the main file (given as argument). I think it's planned for next releases. If needed we can make some tool using watchdog because Python libsass wrapper exposes a clean API to make a sass builder, enjoy the full Python stack!

* libsass only target one file at the time, designers have to know it, even if in practice they never have to care about something else than the "app.scss";

Finally, the libsass port is almost done, this is the important thing, not the stuff around the wrapper choice that can be changed.

**Comment by sveetch** [comment]
Getting back to this, i did have some time to think and talk about it with design integrators.

We have to implement libsass usage as optional, actually every design integrators already have to maintain install with RVM to be able to have ruby environment for Compass 0.x for 2014 past projects and another environment for Compass 1.x for recent projects.

We MUST not urge them again to install another additional environment for this libsass stuff, this would not be fair and not very productive.

So, yes we can urge a new structure with Bourbon and drop Compass mixins usage, but it must compatible with Compass 1.x, so user that don't want to enjoy libsass benefits will be free to stay with Compass 1.x.

Finally what remains to finish this is:

- [ ] Ensure compatibility for Compass 1.x users so it can work with both solution;
- [ ] See about developing a more powerful watcher with something like Watchdog (or at least, warn about it and add an issue to do it);
- [ ] Documentation about libsass install/usage and warning about incompatibility with old projects (Compass 0.x project is totally incompatible, but Compass 1.x projects can be ported manually);
- [ ] Find some alternative of Compass sprite tool and document it;

**Comment by sveetch** [comment]
Compass alternative is on the way with a fullstack Python solution on Boussole project :

https://github.com/sveetch/boussole

**Comment by sveetch** [comment]
Documentation will have to explicitely prohibit about usage of any of Compass SCSS framework to ensure compatibility for non Compass users. Bourbon should be used instead when needed (many Compass components are about vendor prefix that are deprecated on browser since 2/3 years).

**Comment by sveetch** [comment]
Ok it's done with release 1.2.0 (commit b09fc01)
